import type { Metadata } from "next";
import { Ubuntu } from "next/font/google";
import "./styles/globals.css";
import Navbar from "@/app/components/navbar";
import Level2Nav from "./components/level2Nav";
import Footer from "./components/footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const ubuntu = Ubuntu({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ubuntu.className} antialiased`}>
        <div className="mx-wd">
          <Navbar />
          <Level2Nav />
          {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
